name: intervalprogressbar
description: A interval progress bar for Flutter. Horizontal, vertical, colorful and interval progress.
version: 1.0.1
author: StefanJi <jidaoyang@gmail.com>
homepage: https://github.com/stefanJi/IntervalProgressBar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
